# Generated by tools.readthedocs_source. Do not hand-edit generated output.
from pathlib import Path
import shutil

project = 'Auto Manual Library'
html_title = project
extensions = ["myst_parser"]
source_suffix = {".md": "markdown"}
root_doc = "index"
master_doc = "index"
html_theme = "furo"
html_static_path = ["_static"]
html_css_files = ["web_manual.css"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
myst_heading_anchors = 3
suppress_warnings = ["myst.header", "toc.not_included"]


def _copy_manual_assets(app, exception):
    if exception:
        return
    srcdir = Path(app.srcdir)
    outdir = Path(app.outdir)
    for assets_dir in srcdir.glob('**/assets'):
        relative = assets_dir.relative_to(srcdir)
        if '_build' in relative.parts or '_static' in relative.parts:
            continue
        target_dir = outdir / relative
        if target_dir.exists():
            shutil.rmtree(target_dir)
        shutil.copytree(assets_dir, target_dir)


def setup(app):
    app.connect('build-finished', _copy_manual_assets)
