# Generated by tools.readthedocs_source. Do not hand-edit generated output.
project = 'Auto Manual Library'
html_title = project
extensions = ["myst_parser"]
source_suffix = {".md": "markdown"}
root_doc = "index"
master_doc = "index"
html_theme = "furo"
html_static_path = ["_static"]
html_css_files = ["web_manual.css"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
myst_heading_anchors = 3
suppress_warnings = ["myst.header", "toc.not_included"]
